#!/usr/bin/env bash
# freeze.sh — resolve the current version of every tool and write versions.lock,
# pinning the whole set for reproducible installs. Re-run any time to refresh.
#   GitHub tools  -> exact release tag_name (one API call each)
#   conda tools   -> conda-forge latest_version (anaconda.org API)
#   visidata      -> latest on PyPI
set -euo pipefail
source "$(cd "$(dirname "$0")/.." && pwd)/lib.sh"
set +e   # resolve as much as possible; skip anything that can't be reached

out="$LOCKFILE"
tmp="$TMP/versions.lock"
{
  echo "# versions.lock — pinned tool versions. Generated by 'make freeze'."
  echo "# Generated (UTC): $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Columns: name <TAB> channel(gh|conda|pip) <TAB> version-or-tag"
  echo "# Unpin a tool by deleting its line (falls back to latest); delete the"
  echo "# whole file to unpin everything."
} > "$tmp"

log "resolving GitHub release tags (one call per tool)…"
while IFS=$'\t' read -r name repo re bins; do
  [[ -z "$name" || "$name" == \#* ]] && continue
  tag="$(gh_latest_tag "$repo")"
  if [[ -n "$tag" ]]; then
    printf '%s\tgh\t%s\n' "$name" "$tag" >> "$tmp"; ok "$name -> $tag"
  else
    warn "$name: could not resolve tag (left unpinned → latest)"
  fi
done < "$ROOTDIR/binaries.tsv"

log "resolving conda-forge versions…"
for p in tmux zsh datamash parallel pv; do
  v="$(curl -fsSL "https://api.anaconda.org/package/conda-forge/$p" \
        | python3 -c 'import sys,json; print(json.load(sys.stdin).get("latest_version",""))' 2>/dev/null)"
  if [[ -n "$v" ]]; then printf '%s\tconda\t%s\n' "$p" "$v" >> "$tmp"; ok "$p -> $v"
  else warn "$p: conda version unresolved (left unpinned)"; fi
done

log "resolving PyPI version…"
v="$(curl -fsSL https://pypi.org/pypi/visidata/json \
      | python3 -c 'import sys,json; print(json.load(sys.stdin)["info"]["version"])' 2>/dev/null)"
if [[ -n "$v" ]]; then printf 'visidata\tpip\t%s\n' "$v" >> "$tmp"; ok "visidata -> $v"
else warn "visidata: PyPI version unresolved (left unpinned)"; fi

mv "$tmp" "$out"
echo
ok "wrote $out ($(grep -cvE '^[[:space:]]*#' "$out") tools pinned)"
warn "commit versions.lock to reproduce this exact set later"
