#!/usr/bin/env bash
# freeze.sh — resolve the current version of every tool and write versions.lock,
# pinning the whole set for reproducible installs. Re-run any time to refresh.
#   forge tools   -> exact release tag_name from GitHub or Gitea (one call each)
#   conda tools   -> conda-forge latest_version (anaconda.org API)
#   pip tools     -> latest on PyPI
#   gnu tools     -> newest source tarball on ftp.gnu.org (screen, built from source)
#   go            -> newest stable release on go.dev/dl
#   openjdk       -> the Temurin *feature* release (21, 25), not the patch
set -euo pipefail
source "$(cd "$(dirname "$0")/.." && pwd)/lib.sh"
set +e   # resolve as much as possible; skip anything that can't be reached

out="$LOCKFILE"
tmp="$TMP/versions.lock"
{
  echo "# versions.lock — pinned tool versions. Generated by 'make freeze'."
  echo "# Generated (UTC): $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Columns: name <TAB> channel(gh|conda|pip|gnu|go|adoptium) <TAB> version-or-tag"
  echo "# 'gh' means a release tag from the tool's forge (GitHub, or the Gitea"
  echo "# host named in binaries.tsv), not that it came from github.com."
  echo "# 'adoptium' is the one loose pin: it holds a JDK *feature* release (21,"
  echo "# 25) and openjdk.sh installs the newest patch of it, because Temurin"
  echo "# ships security fixes quarterly and pinning past them is a liability."
  echo "# Unpin a tool by deleting its line (falls back to latest); delete the"
  echo "# whole file to unpin everything."
} > "$tmp"

log "resolving release tags from each tool's forge (one call per tool)…"
while IFS=$'\t' read -r name repo re bins; do
  [[ -z "$name" || "$name" == \#* ]] && continue
  tag="$(forge_latest_tag "$repo")"
  if [[ -n "$tag" ]]; then
    printf '%s\tgh\t%s\n' "$name" "$tag" >> "$tmp"; ok "$name -> $tag"
  else
    warn "$name: could not resolve tag (left unpinned → latest)"
  fi
done < "$ROOTDIR/binaries.tsv"

# ollama is not in binaries.tsv (scripts/ollama.sh installs it client-only out
# of a zstd bundle), so resolve its tag here.
tag="$(forge_latest_tag ollama/ollama)"
if [[ -n "$tag" ]]; then
  printf 'ollama\tgh\t%s\n' "$tag" >> "$tmp"; ok "ollama -> $tag"
else
  warn "ollama: could not resolve tag (left unpinned → latest)"
fi

log "resolving conda-forge versions…"
for p in tmux zsh datamash parallel pv goaccess xclip ncdu tree pigz gnu-coreutils; do
  v="$(curl -fsSL "https://api.anaconda.org/package/conda-forge/$p" \
        | python3 -c 'import sys,json; print(json.load(sys.stdin).get("latest_version",""))' 2>/dev/null)"
  if [[ -n "$v" ]]; then printf '%s\tconda\t%s\n' "$p" "$v" >> "$tmp"; ok "$p -> $v"
  else warn "$p: conda version unresolved (left unpinned)"; fi
done

log "resolving PyPI versions…"
for p in visidata llm; do
  v="$(curl -fsSL "https://pypi.org/pypi/$p/json" \
        | python3 -c 'import sys,json; print(json.load(sys.stdin)["info"]["version"])' 2>/dev/null)"
  if [[ -n "$v" ]]; then printf '%s\tpip\t%s\n' "$p" "$v" >> "$tmp"; ok "$p -> $v"
  else warn "$p: PyPI version unresolved (left unpinned)"; fi
done

log "resolving GNU source releases…"
v="$(gnu_latest_version screen)"
if [[ -n "$v" ]]; then printf 'screen\tgnu\t%s\n' "$v" >> "$tmp"; ok "screen -> $v"
else warn "screen: GNU release unresolved (left unpinned → latest)"; fi

# The two language toolchains are opt-in ('make sdks'), but pin them anyway:
# a lockfile that only covers what you happened to install is not a lockfile.
log "resolving language toolchains…"
v="$(curl -fsSL "https://go.dev/dl/?mode=json" \
      | python3 -c 'import sys,json; print(next(r["version"] for r in json.load(sys.stdin) if r.get("stable")))' 2>/dev/null)"
if [[ -n "$v" ]]; then printf 'go\tgo\t%s\n' "$v" >> "$tmp"; ok "go -> $v"
else warn "go: go.dev version unresolved (left unpinned → latest)"; fi

# Deliberately the feature release (17, 21, 25) and not the exact build:
# Temurin ships security patches quarterly and pinning past them is a
# liability, not reproducibility. scripts/openjdk.sh takes the newest patch.
#
# And unlike every other row here, this one is a *choice* — which feature
# release to track — rather than a version to look up. Refreshing it to
# whatever is newest would quietly undo that choice, so an existing pin wins:
# the current LTS is only a fallback for a lockfile that has no openjdk line
# yet. JDK_VERSION overrides both.
v="${JDK_VERSION:-$(lock_get openjdk adoptium)}"
if [[ -n "$v" ]]; then
  ok "openjdk -> Java $v (feature release, kept)"
else
  v="$(curl -fsSL "https://api.adoptium.net/v3/info/available_releases" \
        | python3 -c 'import sys,json; print(json.load(sys.stdin)["most_recent_lts"])' 2>/dev/null)"
  [[ -n "$v" ]] && ok "openjdk -> Java $v (feature release, current LTS)"
fi
if [[ -n "$v" ]]; then printf 'openjdk\tadoptium\t%s\n' "$v" >> "$tmp"
else warn "openjdk: Adoptium LTS unresolved (left unpinned → current LTS)"; fi

mv "$tmp" "$out"
echo
ok "wrote $out ($(grep -cvE '^[[:space:]]*#' "$out") tools pinned)"
warn "commit versions.lock to reproduce this exact set later"
